//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace helloworld {

ref class helloworldConsumer;

public ref class helloworldMethodOneResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Output
    {
        bool get() { return m_interfaceMemberOutput; }
    internal:
        void set(_In_ bool value) { m_interfaceMemberOutput = value; }
    }
    
    static helloworldMethodOneResult^ CreateSuccessResult(_In_ bool interfaceMemberOutput)
    {
        auto result = ref new helloworldMethodOneResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Output = interfaceMemberOutput;
        return result;
    }
    
    static helloworldMethodOneResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new helloworldMethodOneResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    bool m_interfaceMemberOutput;
};

public ref class helloworldJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property helloworldConsumer^ Consumer
    {
        helloworldConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ helloworldConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    helloworldConsumer^ m_consumer;
};

public ref class helloworldGetPropertyOneResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool PropertyOne
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static helloworldGetPropertyOneResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new helloworldGetPropertyOneResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->PropertyOne = value;
        return result;
    }

    static helloworldGetPropertyOneResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new helloworldGetPropertyOneResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    bool m_value;
};

public ref class helloworldSetPropertyOneResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static helloworldSetPropertyOneResult^ CreateSuccessResult()
    {
        auto result = ref new helloworldSetPropertyOneResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static helloworldSetPropertyOneResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new helloworldSetPropertyOneResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

} } } 
