//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace helloworld {

public interface class IhelloworldService
{
public:
    // Implement this function to handle calls to the MethodOne method.
    Windows::Foundation::IAsyncOperation<helloworldMethodOneResult^>^ MethodOneAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ int32 interfaceMemberInput);

    // Implement this function to handle requests for the value of the PropertyOne property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<helloworldGetPropertyOneResult^>^ GetPropertyOneAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the PropertyOne property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<helloworldSetPropertyOneResult^>^ SetPropertyOneAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, bool value);

};

} } } 
